repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.11  # Latest stable version
    hooks:
    -   id: ruff
        types_or: [python, pyi, jupyter]
        args: [
            "--fix",
            "--exit-non-zero-on-fix",
            "--line-length=120",
            "--select=E9,F,I",  # Syntax errors, isort
            "--ignore=F401,F811,F821",  # Common warnings to ignore
            "--per-file-ignores=alembic/versions/*.py:E501,alembic/versions/*.py:F401"
        ]
    -   id: ruff-format
        types_or: [python, pyi, jupyter]
        args: [
            "--line-length=120"
        ]

# Disabling mypy temporarily to speed up pre-commit
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v1.15.0
#     hooks:
#     -   id: mypy
#         additional_dependencies:
#           - types-requests
#           - types-python-dateutil
#           - types-PyYAML
#         args: [--config-file=backend/mypy.ini]
#         exclude: ^tests/|^frontend/
#         types: [python]
#         pass_filenames: true

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: \.(json|md)$
