# This is the configuration file for Ruff.
# For more information, see: https://beta.ruff.rs/docs/settings/

[format]
indent-style = "space"
line-ending = "auto"

[lint]
# Enable these rules
select = ["E9", "F", "I"]  # Syntax errors, Pyflakes, isort

# Ignore these rules
ignore = ["E501", "F401", "F811", "F821"]
