version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: alma-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: sh -c "npm install && npm run dev"
    networks:
      - alma-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: alma-backend-dev
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ./backend/uploads:/app/uploads
    env_file:
      - ./backend/.env
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
      - RELOAD=true
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - alma-network

networks:
  alma-network:
    driver: bridge
