version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
        - VITE_API_BASE_URL=http://localhost:8000
    container_name: alma-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      # API Configuration (using localhost to connect to the backend)
      - VITE_API_BASE_URL=http://localhost:8000
      - NODE_ENV=production

      # Application Settings
      - VITE_APP_NAME=Alma
      - VITE_APP_ENV=production

      # Feature Flags
      - VITE_ENABLE_ANALYTICS=false

      # External Services
      - VITE_SENTRY_DSN=
      - VITE_GA_TRACKING_ID=
    volumes:
      - ./frontend/public:/app/public:ro
    depends_on:
      - backend
    networks:
      - alma-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: alma-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ./backend/uploads:/app/uploads
    environment:
      # Application Settings
      - APP_NAME=Alma
      - APP_ENV=production
      - DEBUG=False

      # Database Configuration (SQLite for simplicity)
      - DATABASE_URL=sqlite:////app/alma.db

      # File Uploads
      - MAX_FILE_SIZE=5242880  # 5MB
      - UPLOAD_DIR=/app/uploads
      - STORAGE_TYPE=filesystem

      # Security
      - SECRET_KEY=change-this-in-production-12345
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440  # 24 hours

      # CORS (must be a JSON array string)
      - CORS_ORIGINS=["http://localhost:3000","http://localhost:5173","http://localhost:8000","http://localhost:8080"]

      # Email Configuration (disabled by default)
      - SMTP_TLS=True
      - SMTP_PORT=587
      - SMTP_HOST=smtp.sendgrid.net
      - SMTP_USER=apikey
      - SMTP_PASSWORD=
      - EMAILS_ENABLED=False
      - EMAILS_FROM_EMAIL=noreply@example.com
      - EMAILS_FROM_NAME="Alma App"
      - ADMIN_EMAIL=admin@example.com

      # Frontend URL
      - FRONTEND_URL=http://localhost:3000

      # Logging
      - LOG_LEVEL=INFO
      - LOG_FORMAT=%(asctime)s - %(name)s - %(levelname)s - %(message)s

      # API Configuration
      - API_V1_STR=/api/v1
      - PROJECT_NAME=Alma API

      # Python
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    networks:
      - alma-network

networks:
  alma-network:
    driver: bridge
